name: "Build to Production"
author: "Paddy Odebiyi"
description: "Custom Github action that writes build folder to production branch"

on:
  paths-ignore:
    - "public/image/**"

runs:
  using: "node16"
  main: "build/index.js"
